### Client requests examples

GET http://127.0.0.1:8000/get_signed/945f5c6c-c2d2-4a36-b0c9-00f847949f40

###
POST http://127.0.0.1:8000/sign
Content-Type: application/octet-stream
sender: Ben Laden
purpose: regular

< /home/ed/Documents/Pepi%20gril%205-10.pdf
