### Client requests examples

GET http://127.0.0.1:8000/get_signed/d42e271a-0b9d-4528-ac92-e0343e430113

###
POST http://127.0.0.1:8000/sign
Content-Type: application/octet-stream
sender: Ben Laden
cert-name: foo

< C:\Users\pisarev\Desktop\tmp\invoice.pdf
