### Client requests examples

GET http://127.0.0.1:8000/health
###
GET http://127.0.0.1:8000/get_signed/ceb22c7d-1ccb-48ed-95f2-f196d4403227
###
POST http://127.0.0.1:8000/sign
Content-Type: application/octet-stream
sender: Ben Laden
cert-name: CSAT

< /home/ed/Downloads/Invoice-3C893A8D-0002.pdf
