### Client requests examples

GET http://127.0.0.1:8000/get_signed/341cfc15-b913-44fa-97bd-b54ec2537cad

###
POST http://127.0.0.1:8000/sign
Content-Type: application/octet-stream
sender: Ben Laden
cert-name: CSAT

< C:\Users\pisarev\Desktop\temp\Back up 12.10.2023.7z
